#!/bin/sh
 
#ssh -t -t igor.beaufils@outils.int.globepayroll.com <<EOF
su igor.beaufils 
 cd /distrib/tools/gitWorkPlace/hello-jenkins
  git pull
  npm install --production
  forever start app.js
exit
EOF

